apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasker
spec:
  selector:
    matchLabels:
      app: flaskerapp
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskerapp
    spec:
      containers:
        - name: flasker
          image: flasker:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8088

