apiVersion: v1
kind: Service
metadata:
  name: flaskerapp-svc-lb
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: flaskerapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
