apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasker
spec:
  selector:
    matchLabels:
      app: flaskerapp
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskerapp
    spec:
      containers:
        - name: flasker
          image: flasker:latest
          imagePullPolicy: Always #See the imagePullPolicy options bellow in comments
          ports:                 
          - containerPort: 8088

# IfNotPresent
# the image is pulled only if it is not already present locally.

# Always
# every time the kubelet launches a container, the kubelet queries the container image registry to resolve the name to an image digest. 
# If the kubelet has a container image with that exact digest cached locally, the kubelet uses its cached image; otherwise, 
# the kubelet pulls the image with the resolved digest, and uses that image to launch the container.

# Never
# the kubelet does not try fetching the image.
# If the image is somehow already present locally, the kubelet attempts to start the container;
# otherwise, startup fails. See pre-pulled images for more details.