apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasker
spec:
  selector:
    matchLabels:
      app: flaskerapp
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskerapp
    spec:
      containers:
        - name: flasker
          image: flasker:latest
          imagePullPolicy: Never #This is for local image pull, to make local image visible for the minikube
          ports:                 #we need to build the image using minikube, here is the command for that
          - containerPort: 8088  # minikube image build -t <image name>:<image tag> . 

